#   File: docker-compose.yml
#   Author: Ben Pennington
#   Description: This yml is for using the docker-compose command
#   to start up the project in docker containers. 

#version needs to be 3.X
version: "3.7"

#list all services
services:
  #Mongo container
  mongo-db:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    image: mongo-db:1.0
    ports:
      - "27017:27017"
    networks:
      back:
        ipv4_address: 192.168.0.2
    restart: unless-stopped 

  #Strapi container
  strapi-frontend:
    build:
      context: .
      dockerfile: Dockerfile-strapi
    image: strapi:1.0
    depends_on:
      - mongo-db
    ports:
      - "1337:1337"
    networks:
      back:
        ipv4_address: 192.168.0.3
      front:
        ipv4_address: 192.168.1.3
    restart: unless-stopped 

  #Vue container
  vue-frontend:
    build: 
      context: .
      dockerfile: Dockerfile-vue
    image: vue:1.0
    depends_on:
      - mongo-db
      - strapi-frontend
    ports:
      - "3000:3000"
    networks:
      front:
        ipv4_address: 192.168.1.4
    restart: unless-stopped 

#set up networking needed
networks:
  back:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"

  front:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
